on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Daisho)
        run: west build -s zmk/app -b daisho -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Daisho DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/daisho.dts.pre.tmp
      - name: Daisho Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 diasho.uf2
      - name: Archive (Daisho)
        uses: actions/upload-artifact@v2
        with:
          name: daisho
          path: daisho.uf2
      - name: West Build (DaishoPad)
        run: west build -s zmk/app -b daishopad -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: DaishoPad DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/daishopad.dts.pre.tmp
      - name: DaishoPad Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 daishopad.uf2
      - name: DaishoPad
        uses: actions/upload-artifact@v2
        with:
          name: daishopad
          path: daishopad.uf2