on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (GW01 Main)
        run: west build -s zmk/app -b gw01_main -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: GW01 (Main) DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/gw01_main.dts.pre.tmp
      - name: GW01 (Main) Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 gw01_main.uf2
      - name: Archive (GW01 Main)
        uses: actions/upload-artifact@v2
        with:
          name: gw01_main
          path: gw01_main.uf2
      - name: West Build (GW01 Macro)
        run: west build -s zmk/app -b gw01_macro -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: GW01 (Macro) DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/gw01_macro.dts.pre.tmp
      - name: GW01 (Macro) Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 gw01_macro.uf2
      - name: Archive (GW01 Macro)
        uses: actions/upload-artifact@v2
        with:
          name: gw01_macro
          path: gw01_macro.uf2